### ISSUE TITLE
no exe and this keeps on showing up 

### ISSUE THREAD

**Issue by Apollogizing** [Rdimo/Hazard-Token-Grabber-V2#104]
Name is: ok
'pyinstaller' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the file specified.
The system cannot find the file specified.
Could Not Find C:\Users\Apollo\Desktop\Hazard-Token-Grabber-V2-master\Modded.spec

generated exe as ok.exe

**Comment by Rdimo** [comment]
open cmd and type `pip install pyinstaller`

**Comment by Apollogizing** [comment]
> open cmd and type `pip install pyinstaller`

still shows the same error

**Comment by saudaalseri** [comment]
> retards dont know how to add python to path thats your own problem not a software problem

I do have it installed

**Comment by Rockkiee** [comment]
oke

**Comment by PapaPlantz** [comment]
Just dont be a sped. simple <3

**Comment by Omexy** [comment]
I'm not sure if this is the quickest method, but this is the method that has worked for me.
1. Install GitBash (https://git-scm.com/downloads)
2. Open it
3. You will be greeted with a menu like this: 
![image](https://user-images.githubusercontent.com/44512200/155863657-0831fd9f-b42f-489d-a3fd-b598ff4271fe.png)
4. Type `python -m pip install pyinstaller`
5. You should see some things happening, with no errors. Once that is done, pyinstaller is now installed on your system!
Hope this helps :)
- **Omexy**

**Comment by Apollogizing** [comment]
> I'm not sure if this is the quickest method, but this is the method that has worked for me.
> 
> 1. Install GitBash (https://git-scm.com/downloads)
> 2. Open it
> 3. You will be greeted with a menu like this:
>    ![image](https://user-images.githubusercontent.com/44512200/155863657-0831fd9f-b42f-489d-a3fd-b598ff4271fe.png)
> 4. Type `python -m pip install pyinstaller`
> 5. You should see some things happening, with no errors. Once that is done, pyinstaller is now installed on your system!
>    Hope this helps :)
> 
> * **Omexy**

sadly it didn't work. I've been trying to redownload python over and over but everytime I try to put the name I want for the exe it doesn't work

**Comment by Omexy** [comment]
Message me on Discord (Omexy#1234), I'll try to help you out there.

**Comment by Omexy** [comment]
I just helped someone with the **exact same issue**, turns out that they didn't configure their PATH directory correctly. Here are some steps to sort it out:
1. Open Control Panel
2. Search "environment" in the Searchbar
3. Click "Edit environment variables for your account"
4. Double-click on Path
5. Press "New"
6. Paste `%USERPROFILE%\AppData\Local\Programs\Python\Python310\Scripts\` and press Enter.
7. Repeat but with `%USERPROFILE%\AppData\Local\Programs\Python\Python310\` instead.
8. It should look like this now but with less additions (you probably have 3 entries): 
![image](https://user-images.githubusercontent.com/44512200/155866830-c8db5bf0-fb8a-4c95-805b-307703e6288a.png)
9. You can now close everything and your issue should be solved! 

Hope this helps! :)
Contact me on Discord (Omexy#1234) if you run into any issues.

- **Omexy**
