### ISSUE TITLE
unknown fatal error

### ISSUE THREAD

**Issue by niggp** [Rdimo/Hazard-Token-Grabber-V2#114]
This was working fine until I shit my computer off for a while. Came back and after downloading it again. Keep getting this message. Any fix?

![ridmo](https://user-images.githubusercontent.com/100456434/156851118-8957307a-94fd-4db4-b9fb-926192f5eafb.PNG)

**Comment by Omexy** [comment]
Hey niggp,

I believe that you need to manually compile your Python file into an EXE file since from what I'm looking at in the image, the error is occurring in the **application of HazardNuker**. Please feel free to correct me if I'm wrong. Anyways, here are the steps to manually compile the file:

1. Open the directory/folder where the `HazardNuker` application is located.
2. You should then see the files `*name*.spec`, `*name*.py`, `build` (folder) and `dist` (folder).
3. Delete the path at the top of File Explorer and replace it **only** with `cmd`. It should look like this (ignore the two entries below cmd): 
![image](https://user-images.githubusercontent.com/44512200/156812566-78d8c734-9645-4f89-9c0f-de67501e97f0.png)
4. Once your Command Prompt window is open, it will be in the directory of where the `HazardNuker` application is. For example, here is what it looks like for me: 
![image](https://user-images.githubusercontent.com/44512200/156812748-329cdce3-8ff7-4a6d-a1d2-25da273d1982.png)
5. Type `pyinstaller --onefile --clean --noconsole *name*.py`. In my case, it will be `test` instead of `*name*`.
6. The compilation of the EXE should begin and lots of lines in the application should appear again as seen in `step 6` of the previous instruction list.
7. If everything went well, the last line will say `Building EXE from EXE-00.toc completed successfully.` and the EXE will be located inside the `dist` folder with the name you have chosen. Here is what the directory should look like:
![image](https://user-images.githubusercontent.com/44512200/156813761-0e0a1811-0f19-4681-947d-93a1192ebc01.png)
Your directory might not include `chromedriver.exe` and the name of the `Python` file (`test.py`) & `SPEC` file (`test.spec`) will most likely be different because of your input on `step 4` of the first instruction set.

Hope this helps! :) Contact me on Discord `Omexy#1234` or join the Cheataway Discord server (https://discord.gg/kXFjPzudtY) for support.

- **Omexy**

**Comment by addi00000** [comment]
Try running:

`python -m PyInstaller --onefile --noconsole -n monkey main.py`

in cmd in the same directory.

**Comment by niggp** [comment]
> 

This is an error for Hazard Token Grabber. Not Hazard Nuker

**Comment by addi00000** [comment]
> > 
> 
> This is an error for Hazard Token Grabber. Not Hazard Nuker

thats why its an issue on Hazard Token Grabber.

**Comment by Omexy** [comment]
> 

Apologies, how did you try to compile your EXE file if you could explain please?

**Comment by niggp** [comment]
> > 
> 
> Apologies, how did you try to compile your EXE file if you could explain please?

I didnt compile it. Usually did it on its own.

**Comment by addi00000** [comment]
> 

python -m PyInstaller --onefile --noconsole -n monkey main.py

**Comment by niggp** [comment]
> 

DId this and it did stuff that I have never see from this. I deleted all of the items and am reinstalling just grabber

**Comment by Omexy** [comment]
> > > 
> > 
> > 
> > Apologies, how did you try to compile your EXE file if you could explain please?
> 
> I didnt compile it. Usually did it on its own.

Ahhh I see, follow **addi00000**'s and my advice by following the steps I have put in at the top for **HazardNuker** but they **also work for this situation**. Let me know if they don't work.

**Comment by addi00000** [comment]
if a `dist` folder is created thats where your exe is

**Comment by Omexy** [comment]
^^^
Addi is correct, that's what was also listed in my steps.

**Comment by niggp** [comment]
> if a `dist` folder is created thats where your exe is

dist was created just with a py file. Not exe

**Comment by Omexy** [comment]
Can you take a screenshot of your directory and upload it here?

> > if a `dist` folder is created thats where your exe is
> 
> dist was created just with a py file. Not exe

**Comment by addi00000** [comment]
**Example:**
https://user-images.githubusercontent.com/81730200/156855665-72d27706-a597-4a1e-865a-ea53655bc4b3.mp4

instead of putting `print("HW!")` like I did; copy/paste the [raw main file](https://raw.githubusercontent.com/Rdimo/Hazard-Token-Grabber-V2/master/main.py) into an empty py script and execute the command.

**Comment by niggp** [comment]
> 
![Capture](https://user-images.githubusercontent.com/100456434/156856081-a87b2495-44a2-4b94-88e8-a210db0ef14c.PNG)
Heres the new error. Discord webhook is not wrong though?

**Comment by niggp** [comment]
> **Example:** https://user-images.githubusercontent.com/81730200/156855665-72d27706-a597-4a1e-865a-ea53655bc4b3.mp4
> 
> instead of putting `print("HW!")` like I did; copy/paste the [raw main file](https://raw.githubusercontent.com/Rdimo/Hazard-Token-Grabber-V2/master/main.py) into an empty py script and execute the command.

Im about to leave for dinner. But when I get back I could hop in a discord call with one of yall. chacha#0001

**Comment by Omexy** [comment]
> > **Example:** https://user-images.githubusercontent.com/81730200/156855665-72d27706-a597-4a1e-865a-ea53655bc4b3.mp4
> > instead of putting `print("HW!")` like I did; copy/paste the [raw main file](https://raw.githubusercontent.com/Rdimo/Hazard-Token-Grabber-V2/master/main.py) into an empty py script and execute the command.
> 
> Im about to leave for dinner. But when I get back I could hop in a discord call with one of yall. chacha#0001

Sent!

**Comment by addi00000** [comment]
> ![Capture](https://user-images.githubusercontent.com/100456434/156856081-a87b2495-44a2-4b94-88e8-a210db0ef14c.PNG)
> Heres the new error. Discord webhook is not wrong though?

You didn’t put your webhook into the webhook line which means when it performs a POST request it fails

**Comment by addi00000** [comment]
> 

Line 19 I think

**Comment by niggp** [comment]
> > 
> 
> Line 19 I think

It is in line 19 and it still does not work

**Comment by Rockkiee** [comment]
did I ask?

**Comment by FuckingToasters** [comment]
> This was working fine until I shit my computer off for a while. Came back and after downloading it again. Keep getting this message. Any fix?
> 
> ![ridmo](https://user-images.githubusercontent.com/100456434/156851118-8957307a-94fd-4db4-b9fb-926192f5eafb.PNG)

just install pyinstaller lol
