### ISSUE TITLE
you skidded discord token injector from pirvate stealer. you poor

### ISSUE THREAD

**Issue by otar120** [Rdimo/Hazard-Token-Grabber-V2#362]
get that hard work in your ass

**Comment by Mago126** [comment]
pirate stealer aint even working lol

**Comment by Rdimo** [comment]
> get that hard work in your ass

lmao calling it "skidding" would take it a step further, 2 things you're missing, I gave cred and of course asked him at first if it was okey which he said it was. Right now the [injection](https://github.com/Rdimo/Discord-Injection) isn't even near in similarity to Stanley's injection since I've modified it to work with the latest discord patches and added loads more features + maintaining it better. Take the skid word and shove it up you're fat ass and you might just realize what it means. I can send you $5 too if you'd like so you can afford to take the buss to school and learn what shit means.

**Comment by afroshyi** [comment]
> get that hard work in your ass

boy what the hell boy

**Comment by otar120** [comment]
@Rdimo you just changed discord-core-1 to discord-core-2 so you have not changed much. you token grabber is literally nothing without injector so stfu. i don't need your 5$ idiot. i can make x10 times more in 1 day then you in the whole year

**Comment by RandomVersion** [comment]
> > get that hard work in your ass
> 
> lmao calling it "skidding" would take it a step further, 2 things you're missing, I gave cred and of course asked him at first if it was okey which he said it was. Right now the [injection](https://github.com/Rdimo/Discord-Injection) isn't even near in similarity to Stanley's injection since I've modified it to work with the latest discord patches and added loads more features + maintaining it better. Take the skid word and shove it up you're fat ass and you might just realize what it means. I can send you $5 too if you'd like so you can afford to take the buss to school and learn what shit means.

i would take those 5$ if you want too

**Comment by otar120** [comment]
@Rdimo you made premium shit of your grabber. why should people pay for free stuff? so  i coded one for everyone. you can call it hazard token grabber v2 or whatever. stop crying for losing your customers. your injector code is from stenley. THERE IS NOTHING CODED BY YOU. hazard token grabber v2 can be coded by 9 years old kid with basic knowledge of python. don't get mad, face the reality. (also TOUCH the grass)

**Comment by dekrypted** [comment]
Bro this whole convo is retarded 😂

**Comment by Rdimo** [comment]
> 

bro what, I don't sell anything 💀💀 I'm planning to sell a stealer yes but its not done yet. All my stuff on github is free tf are you even talking about 😂 If anything its stanley losing customers since his injection isnt working + mines better, more supported, more features, maintained, and actually working and its free

**Comment by Rdimo** [comment]
> 

if 9 y/o can code this, aren't you like 2 months old then?

**Comment by Rdimo** [comment]
> @Rdimo you made premium shit of your grabber. why should people pay for free stuff? so i coded one for everyone. you can call it hazard token grabber v2 or whatever. stop crying for losing your customers. your injector code is from stenley. THERE IS NOTHING CODED BY YOU. hazard token grabber v2 can be coded by 9 years old kid with basic knowledge of python. don't get mad, face the reality. (also TOUCH the grass)

if 9 y/o can code this, aren't you like 2 months old then?

**Comment by 7myra-gg** [comment]
🌱・Inspiration/Credits
Discord-Injection is heavily inspired by stanleys injection but has been upgraded quite alot since
A few snippets are from his injection so huge cred to stan

btw @otar120

**Comment by Rdimo** [comment]
> 🌱・Inspiration/Credits Discord-Injection is heavily inspired by stanleys injection but has been upgraded quite alot since A few snippets are from his injection so huge cred to stan
> 
> btw @otar120

ye and that

**Comment by Rdimo** [comment]
just gonna delete this don't want anymore fire buildup
