### ISSUE TITLE
Spastic Skid Moment

### ISSUE THREAD

**Issue by omnituensaeternum** [Rdimo/Hazard-Token-Grabber-V2#383]
"the code in the readme is ass and regex can drastically be improved" 
__Originally posted by @Rdimo in https://github.com/Rdimo/Hazard-Token-Grabber-V2/issues/370#issuecomment-1152884847__

Your Regex:
![image](https://user-images.githubusercontent.com/49354579/173463010-c9a0a1b2-2372-4b7e-9490-f650da7ced87.jpeg)

The New Regex:
![image](https://user-images.githubusercontent.com/49354579/173463032-845336b8-ee44-4fe7-9e98-ac694fa3d36f.jpeg)

Spastic fuck you literally skidded it. Why you talking shit on the crap you stole and used?

**Comment by GodFather227** [comment]
Nigga what

**Comment by Rdimo** [comment]
💀💀 you know I made both the regexes, the reason the second one is so long was because I haven't worked with regexes for along time

![image](https://user-images.githubusercontent.com/80375661/173568507-e3c432cf-8af3-40ff-83f8-27f40dec839e.png)
as you can see here at 2022-05-01 I made the regex better and going to that commit you will see 
![image](https://user-images.githubusercontent.com/80375661/173568809-b9ee1f66-c3e1-49d4-85e9-00f855a99fa1.png)
![image](https://user-images.githubusercontent.com/80375661/173568781-04c6f019-2943-4dcf-9aab-5c21e3206852.png)

you can take a look at it for yourself [here](https://github.com/Rdimo/Hazard-Token-Grabber-V2/commit/aa8909e16683ea07c3066963f291dfa7ee4f25af)

and as you can see here
![image](https://user-images.githubusercontent.com/80375661/173569008-7ae214ef-789d-47e2-b010-4ab9dfc1852f.png)
at 2022-04-14 I added the first regex which was ass and inefficient, but it worked. If we look at [this](https://github.com/NobodyWouldEverUseThis7/Token-encryption-writeup) skidded repo that you retardly post around on every github repo there is. You will probably see this if you have eyes
![image](https://user-images.githubusercontent.com/80375661/173569372-d5a8c9cc-854f-4b4f-898d-39764e2788e8.png)
it was made 10 days ago which isn't even close to near when I published and released my first regex. Now shut your fat ass up and go cry to mom before talking again

**Comment by xvzontop** [comment]
You my friend are a retard

**Comment by Rdimo** [comment]
> You my friend are a retard

fr, @omnituensaeternum worked hard to get his 🤡 trophy
